.env.custom_node, .env.testnet, consensusInfoClient.js, mirrorNodeClient.js, package-lock.json, package.json
This PR removes the static wait time before asking mirror node for data and replaces it with a dynamic wait.
=> Feat: Add dynamic wait for mirror node

test-specifications/deleteAccount.md
This PR adds the document explaining the account delete transaction tests.
Fixes https://github.com/hashgraph/hedera-sdk-tck/issues/22
=> Chore: Create deleteAccount.MD

test-specifications/updateAccountKey.md, test-specifications/updateAccountMemo.md, test/account/test_UpdateAccountKey.js
This PR adds MD's for Account Update Memo and Account Update Key tests.
Fixes https://github.com/hashgraph/hedera-sdk-tck/issues/21
=> Chore: Create updateAccountKey.MD and updateAccountMemo.MD

test-specifications/getAccountBalance.md
This PR adds the documentation for `AccountBalanceQuery` E2E tests.
Fixes #28 
**Checklist**
=> Add `AccountBalanceQuery` E2E test documentation

.prettierignore, .prettierrc.js, README.md, client.js, consensusInfoClient.js, eslint.config.js, mirrorNodeClient.js, package-lock.json, package.json, setup_Tests.js, test/crypto-service/test_AccountInfo.js, test/crypto-service/test_accountCreateTransaction.js, test/crypto-service/test_accountDeleteTransaction.js, test/crypto-service/test_accountUpdateTransaction.js, test/test_Template.js
This PR adds and configures ESLint and Prettier tools to the project, enhancing code quality and consistency. Applied formatting and fixed linting issues across the existing JavaScript code.
#240 
**Checklist**
=> feat: Add and configure ESLint and Prettier tools.

mirrorNodeClient.js, test/crypto-service/test_accountCreateTransaction.js, test/crypto-service/test_accountUpdateTransaction.js
This PR updates the Mirror Node Client to ensure compatibility with the latest Swagger specifications, addressing discrepancies in API responses. Fixed some errors that occurred after the update.
#244
=> fix: Update Mirror Node Client class 

src/tests/token-service/test-token-associate-transaction.ts, src/tests/token-service/test-token-burn-transaction.ts, src/tests/token-service/test-token-dissociate-transaction.ts, src/tests/token-service/test-token-freeze-transaction.ts, src/tests/token-service/test-token-grant-kyc-transaction.ts, src/tests/token-service/test-token-mint-transaction.ts, src/tests/token-service/test-token-revoke-kyc-transaction.ts, src/tests/token-service/test-token-unfreeze-transaction.ts, src/utils/helpers/token.ts
Description:
This PR is fixing the missing parameters in `getTokenRelationships` and `createToken` methods.
Related issue(s):
#317 
Checklist
=> chore(fix): Fixed missing parameters

github/workflows/pr_check.yml
This PR introduces a workflow that verifies whether the PR title follows best practices.
=> feat: Added PR title check workflow

MAINTAINERS.md
Maintainers file added as described at https://lf-decentralized-trust.github.io/governance/governing-documents/MAINTAINERS-file.html
=> chore: Create MAINTAINERS.md

src/tests/crypto-service/test-account-update-transaction.ts, src/tests/token-service/test-token-create-transaction.ts, src/tests/token-service/test-token-update-transaction.ts, src/utils/constants/key-type.ts, src/utils/constants/test-paths.ts
There were a few flaky tests showing up in CI, this PR fixes the flakiness on those.
Fixes #369 
**Checklist**
=> fix: flaky tests

.github/workflows/test_regression.yml
This PR enhances the regression workflow by adding two additional test suites into the CI checks.
**Checklist**
=> chore: Added `TransferCrypto` and `TokenWipe` in regression workflow

README.md, Taskfile.yaml
This PR introduces a clear and structured description of the TCK release process, along with additional task commands to streamline and support the release workflow.
**Checklist**
=> feat: Described and optimized release process

package-lock.json, package.json, src/services/Client.ts
This PR removes the manual checks for network connectivity issues, as we have introduced a [fix](https://github.com/hiero-ledger/hiero-sdk-js/pull/3077) in the JS SDK.
#363 
**Checklist**
=> chore(fix): Removed skip on network connectivity issues

src/tests/crypto-service/test-account-create-transaction.ts, src/tests/crypto-service/test-account-delete-transaction.ts, src/tests/crypto-service/test-account-update-transaction.ts, src/tests/crypto-service/test-transfer-transaction.ts, src/tests/token-service/test-token-airdrop-transaction.ts, src/tests/token-service/test-token-associate-transaction.ts, src/tests/token-service/test-token-burn-transaction.ts, src/tests/token-service/test-token-create-transaction.ts, src/tests/token-service/test-token-delete-transaction.ts, src/tests/token-service/test-token-dissociate-transaction.ts, src/tests/token-service/test-token-fee-schedule-update-transaction.ts, src/tests/token-service/test-token-freeze-transaction.ts, src/tests/token-service/test-token-grant-kyc-transaction.ts, src/tests/token-service/test-token-mint-transaction.ts, src/tests/token-service/test-token-pause-transaction.ts, src/tests/token-service/test-token-revoke-kyc-transaction.ts, src/tests/token-service/test-token-unfreeze-transaction.ts, src/tests/token-service/test-token-unpause-transaction.ts, src/tests/token-service/test-token-update-transaction.ts, src/tests/token-service/test-token-wipe-transaction.ts, src/utils/helpers/key.ts
This PR extracts the repeated key generation logic into helper functions and replaces the duplicated code across all relevant methods.
#376 
**Checklist**
=> chore(refactor): Repeated key generation logic

src/tests/crypto-service/test-account-allowance-approve-transaction.ts, src/utils/helpers/allowances.ts, src/utils/models/Allowance.ts
This PR extracts the repeated JSONRPC approve allowance request logic into helper functions and replaces the duplicated code across all relevant methods in the test-account-allowance-approve-transaction.ts  file.
**Related issue(s):**
#376 
**Checklist**
=> chore(refactor): Repeated approveAllowance params

src/services/ConsensusInfoClient.ts, src/tests/file-service/test-file-update-transaction.ts
This PR implements the `FileUpdateTransaction` tests documented in `test-specifications/file-service/FileUpdateTransaction.md`. 
#424 
**Checklist**
=> feat(updateFile): Implement `FileUpdateTransaction` E2E tests: TCK

.github/workflows/test_regression.yml, README.md, docs/test-specifications/common/index.md, docs/test-specifications/crypto-service/TransferTransaction.md, docs/test-specifications/file-service/FileAppendTransaction.md, docs/test-specifications/file-service/FileCreateTransaction.md, docs/test-specifications/file-service/FileUpdateTransaction.md, docs/test-specifications/file-service/index.md, docs/test-specifications/token-service/TokenAirdropCancelTransaction.md, docs/test-specifications/token-service/TokenAirdropClaimTransaction.md, docs/test-specifications/token-service/TokenAirdropTransaction.md, docs/test-specifications/token-service/TokenAssociateTransaction.md, docs/test-specifications/token-service/TokenBurnTransaction.md, docs/test-specifications/token-service/TokenCreateTransaction.md, docs/test-specifications/token-service/TokenDeleteTransaction.md, docs/test-specifications/token-service/TokenDissociateTransaction.md, docs/test-specifications/token-service/TokenFeeScheduleUpdateTransaction.md, docs/test-specifications/token-service/TokenFreezeTransaction.md, docs/test-specifications/token-service/TokenGrantKycTransaction.md, docs/test-specifications/token-service/TokenMintTransaction.md, docs/test-specifications/token-service/TokenPauseTransaction.md, docs/test-specifications/token-service/TokenRejectTransaction.md, docs/test-specifications/token-service/TokenRevokeKycTransaction.md, docs/test-specifications/token-service/TokenUnfreezeTransaction.md, docs/test-specifications/token-service/TokenUnpauseTransaction.md, docs/test-specifications/token-service/TokenUpdateTransaction.md, docs/test-specifications/token-service/TokenWipeTransaction.md, docs/test-specifications/token-service/index.md, src/utils/constants/test-paths.ts
This PR gets the TCK ready for the v0.4.0 release, adds tests to CI, and makes some updates and fixes to various docs.
=> chore: v0.4.0 release

docs/test-specifications/file-service/FileDeleteTransaction.md
**Description:**
This PR adds the test specifications for `FileDeleteTransaction` fields.
**Related Issue(s):**
Fixes #442 
**Checklist**
=> docs: Add test specifications for `FileDeleteTransaction`

src/tests/crypto-service/test-account-create-transaction.ts, src/utils/constants/key-type.ts
Fixes #
**Notes for reviewer**:
**Checklist**
=> fix: Remove randomness

src/services/MirrorNodeClient.ts, src/tests/topic-service/test-topic-create-transaction.ts, src/tests/topic-service/test-topic-delete-transaction.ts, src/tests/topic-service/test-topic-message-submit-transaction.ts
This PR implements the TopicMessageSubmitTransaction tests documented in test-specifications/topic-service/TopicMessageSubmitTransaction.md
Fixes #488
**Checklist**
=> feat: impement TopicMessageSubmitTransaction tests

src/tests/contract-service/test-contract-update-transaction.ts
Implemented Contract Update Transaction tests
Fixes #496 
**Checklist**
=> feat: ContractUpdateTransaction tests

src/tests/contract-service/test-contract-create-transaction.ts, src/tests/contract-service/test-contract-delete-transaction.ts
=> chore: skip contract tests

src/tests/crypto-service/test-account-create-transaction.ts
Fixes #
**Notes for reviewer**:
**Checklist**
=> fix: remove operator balance race condition

.github/workflows/pr_check.yml
- Updates the PR Formatting to properly use the main branches PR formatting checks.
Fixes #519
=> ci(bug): Fix PR Checks

.github/workflows/compatibility.yml, .github/workflows/test_regression.yml
Fixes JS SDK dependency bug.
Fixes #
**Notes for reviewer**:
**Checklist**
=> ci: Fix node dependencies

.github/workflows/go_compatibility.yml, .github/workflows/js_compatibility.yml
Fixes #
**Notes for reviewer**:
**Checklist**
=> fix: bump mirror node version

docs/test-specifications/crypto-service/AccountBalanceQuery.md, src/tests/crypto-service/test-account-balance-query-transaction.ts
This PR implements `AccountBalanceQuery` tests and updates the doc
Fixes #50 
**Checklist**
=> feat: add `AccountBalanceQuery` tests
